### PR TITLE
Update myalbum_downloader.py

### PR DESCRIPTION
**Pull request by rock3r**
The script as it currently is doesn't work anymore. This update fixes it and adds some functionality on top.

### CODE REVIEW

**Comment by Gertje823** [comment]
This doesn't seem to work for me. 
I tried https://myalbum.com/album/jtwATxKy4gZu/
Do you have an example URL?

**Comment by rock3r** [comment]
I tested with this https://myalbum.com/album/tZqckzSnbv4Crj/

**Comment by Gertje823** [comment]
Hmmm.. your url is working, but when I try a couple others and get this error:
```🌍 Enter MyAlbum URL:
https://myalbum.com/album/jtwATxKy4gZu/
  ⏳ Downloading page...
  ⏳ Parsing page...
    ℹ️  Album title: Taarten
Traceback (most recent call last):
  File "myalbum_downloader.py", line 23, in <module>
    contents = rootJson["props"]["pageProps"]["album"]["data"]["contents"]
KeyError: 'contents'```

**Comment by rock3r** [comment]
Hmmm I guess the title can be in multiple places. This means there may be multiple ways data is presented, which would explain why the original script didn't work for the album I have coded against...

**Comment by Gertje823** [comment]
I merged the PR into the main branch and edited it so it support the 'legacy' albums and 'new' albums.

**Pull request merged**
